build:
  environment:
    mongodb: true
    php:
      version: "7.1"
      ini:
        memory_limit: "-1"
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover'
        coverage:
          file: 'coverage.clover'
          format: 'clover'

tools:
  # Code Sniffer
  php_code_sniffer:
    enabled: true
    config:
      standard: PSR2
    filter:
      paths:
        - 'src/*'
        - 'boot/*'
        - 'tests/*'
  # PHP CS Fixer.
  php_cs_fixer:
    enabled: true
    config:
      level: all
    filter:
      paths:
        - 'src/*'
        - 'boot/*'
        - 'tests/*'
  # Copy/Paste Detector
  php_cpd:
    enabled: true
    excluded_dirs:
      - tests
      - vendor
  # PHP Mess Detector (http://phpmd.org).
  php_mess_detector:
    enabled: true
    filter:
      paths:
        - 'src/*'
        - 'boot/*'
        - 'tests/*'
  # Analyzes the size and structure of a PHP project.
  php_pdepend:
    enabled: true
    excluded_dirs:
      - tests
      - vendor
  # Analyzes the size and structure of a PHP project.
  php_loc:
    enabled: true
    excluded_dirs:
      - tests
      - vendor
  # Code Coverage
  php_code_coverage: true
  # Runs Scrutinizer's PHP Analyzer Tool
  # https://scrutinizer-ci.com/docs/tools/php/php-analyzer/config_reference
  php_analyzer: true
  # PHP Code Similarity Analyzer
  php_sim: true
  # Tracking Code Changes/Stability
  php_changetracking: true
  # Security Advisory Checker
  sensiolabs_security_checker: true


checks:
  php: true

coding_style: true
