build:
  dependencies:
    before:
      - pecl channel-update pecl.php.net
  environment:
    postgresql: false
    redis: false
    mongodb: false
    php:
      version: "7.1"
      ini:
        memory_limit: "-1"
  tests:
    override:
      -
        # PHP Mess Detector.
        command:  './vendor/bin/phpmd ./ xml ./phpmd.xml --suffixes php --reportfile ./report-phpmd.xml'
        analysis:
          file:   'report-phpmd.xml'
          format: 'pmd-xml'
      -
        # Copy/Paste Detector
        command:  './vendor/bin/phpcpd --exclude=vendor --exclude=tests --fuzzy --log-pmd=./report-phpcpd.xml ./'
        analysis:
          file:   'report-phpcpd.xml'
          format: 'pmd-xml'

checks:
  php: true

tools:
  # Code Coverage
  php_code_coverage: false
  external_code_coverage:
    timeout: 600
    runs: 3
  # Code Sniffer
  php_code_sniffer:
    enabled: true
    config:
      standard: phpcs.xml
  # Analyzes the size and structure of a PHP project.
  php_pdepend:
    enabled: true
    excluded_dirs:
      - tests
      - vendor
  # Analyzes the size and structure of a PHP project.
  php_loc:
    enabled: true
    excluded_dirs:
      - tests
      - vendor
  # PHP CS Fixer.
  php_cs_fixer: true
  # Runs Scrutinizer's PHP Analyzer Tool
  php_analyzer: true
  # Runs Scrutinizer's PHP Code Similarity Analyzer
  php_sim: true
  # Tracking Code Changes/Stability
  php_changetracking: true
  # Security Advisory Checker
  sensiolabs_security_checker: true
