build:
  dependencies:
    before:
      - pecl channel-update pecl.php.net
  environment:
    postgresql: false
    redis: false
    mongodb: false
    php:
      version: "7.1"
      ini:
        memory_limit: "-1"

checks:
  php: true

tools:
  # External code coverage
  external_code_coverage:
    enabled: true
    timeout: 600
    filter:
      paths: ["src/*"]

  # Scrutinizer's code coverage
  php_code_coverage:
    enabled: false
    test_command: phpunit -c phpunit.xml.dist
    filter:
      paths: ["src/*"]

  # Code Sniffer
  php_code_sniffer:
    enabled: true
    config:
      standard: phpcs.xml.dist
    filter:
      paths: ["boot/*", "src/*", "tests/*"]

  # PHP CS Fixer.
  php_cs_fixer:
    enabled: true
    config:
      level: all
    filter:
      paths: ["boot/*", "src/*", "tests/*"]

  # PHP Mess Detector
  php_mess_detector:
    enabled: true
    config:
      ruleset: phpmd.xml.dist
    filter:
      paths: ["boot/*", "src/*"]

  # Analyzes the size and structure of a PHP project.
  php_loc:
    enabled: true
    excluded_dirs: ["build", "resources", "tests", "vendor"]

  # Analyzes the size and structure of a PHP project.
  php_pdepend:
    enabled: true
    excluded_dirs: ["build", "resources", "tests", "vendor"]

  # PHP Copy-Paste detector.
  php_cpd:
    enabled: true
    excluded_dirs: ["build", "resources", "tests", "vendor"]

  # Runs Scrutinizer's PHP Code Similarity Analyzer
  php_sim:
    enabled: true
    filter:
      excluded_paths: ["build/", "resources/", "tests/", "vendor/"]

  # Runs Scrutinizer's PHP Analyzer Tool
  php_analyzer:
    enabled: true
    filter:
      paths: ["src/*", "tests/*"]

  # Tracking Code Changes/Stability
  php_changetracking: true
  # Security Advisory Checker
  sensiolabs_security_checker: true
