language: php
sudo: false

os:
  - linux

env:
  global:
    - PHPUNIT_LOGS_DIR=./build/logs/phpunit

php:
  - 7.1

services:
  - mongodb

before_install:
  - pecl channel-update pecl.php.net
  - pecl install mongodb
  - composer self-update --stable

install:
  - composer install --no-interaction --no-suggest

script:
  - ./build/scripts/phpunit.sh
  - ./build/scripts/phpcs.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ${PHPUNIT_LOGS_DIR}/report-coverage.clover.xml
