language: php
dist: xenial
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

addons:
  apt:
    packages:
    - php-mongodb

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --stable
  - composer --version

install:
  - composer --verbose install

script:
  - ./bin/phpunit
