language: php
sudo: false

os:
  - linux

php:
  - 7.1

services:
  - mongodb

before_install:
  - sudo apt-get update
  - pecl channel-update pecl.php.net
  - pecl install mongodb
  - composer self-update --stable

install:
  - composer install --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpcs --standard=phpcs.xml.dist

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
